// Copyright (c) 2026 Christian Flessa. All rights reserved.
// This file is licensed under the MIT license. See LICENSE in the project root for more information.
namespace ShadowDrop.Cli;

using System.Reflection;

/// <summary>
/// Resolves the CLI's version from the assembly informational version generated by the build pipeline
/// (<c>SetInformationalVersion</c>), used by both <c>--version</c> and the decorated banner so they cannot drift.
/// </summary>
internal static class CliVersion
{
    public static String Current { get; } = Resolve();

    private static String Resolve()
    {
        var informationalVersion = typeof(CliVersion).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        if (String.IsNullOrWhiteSpace(informationalVersion))
        {
            return "0.0.0";
        }

        // Local and CI builds append "+<source-revision-id>" to the informational version; only the
        // semantic version portion belongs in user-facing version output.
        var buildMetadataIndex = informationalVersion.IndexOf('+');
        return buildMetadataIndex < 0 ? informationalVersion : informationalVersion[..buildMetadataIndex];
    }
}
